global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'api-lstm-monitor'

scrape_configs:
  - job_name: 'api-lstm'
    static_configs:
      - targets: ['api-lstm:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
